[project]
name = "myrag"
version = "0.1.0"
description = "Simple RAG implementation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["psycopg2-binary",
				"dotenv",
				"pdfplumber",
				"sentence_transformers"]
